using System.Globalization;
using System.Text.RegularExpressions;

namespace RestaurantMenuPlatform.Web.Services;

/// <summary>
/// Central application-owned UI copy. Business values should be selected from
/// their English/Arabic fields by the view or application service.
/// </summary>
public static class UiText
{
    private static readonly IReadOnlyDictionary<string, string> Arabic =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Administration navigation"] = "التنقل الإداري",
            ["Skip to content"] = "الانتقال إلى المحتوى",
            ["Restaurant workspace"] = "مساحة عمل المطعم",
            ["Dashboard"] = "لوحة المعلومات",
            ["Tenant Dashboard"] = "لوحة معلومات المستأجر",
            ["Restaurant"] = "المطعم",
            ["Overview"] = "نظرة عامة",
            ["Branches"] = "الفروع",
            ["Branch"] = "الفرع",
            ["branch(es)"] = "فرع/فروع",
            ["categories"] = "فئات",
            ["items"] = "منتجات",
            ["product(s)"] = "منتج/منتجات",
            ["image(s)"] = "صورة/صور",
            ["Menu management"] = "إدارة القوائم",
            ["Menus"] = "القوائم",
            ["Menu Items"] = "عناصر القائمة",
            ["Menu items"] = "عناصر القائمة",
            ["Menu"] = "القائمة",
            ["Catalog"] = "الكتالوج",
            ["Products"] = "المنتجات",
            ["Product"] = "المنتج",
            ["Ingredients"] = "المكونات",
            ["Allergens"] = "مسببات الحساسية",
            ["Modifiers"] = "الإضافات",
            ["Operations"] = "العمليات",
            ["Pricing"] = "التسعير",
            ["QR codes"] = "رموز QR",
            ["Active QR Codes"] = "رموز QR النشطة",
            ["Insights"] = "التحليلات",
            ["Analytics"] = "التحليلات",
            ["Administration"] = "الإدارة",
            ["Users & roles"] = "المستخدمون والأدوار",
            ["User"] = "مستخدم",
            ["Users"] = "المستخدمون",
            ["Lookup types"] = "أنواع القوائم المرجعية",
            ["Lookup values"] = "قيم القوائم المرجعية",
            ["Subscription"] = "الاشتراك",
            ["Audit"] = "سجل التدقيق",
            ["Platform plans"] = "خطط المنصة",
            ["Platform"] = "المنصة",
            ["Restaurants"] = "المطاعم",
            ["Platform administration"] = "إدارة المنصة",
            ["Provision and support restaurant workspaces from one platform view."] = "إنشاء وإدارة مساحات عمل المطاعم من شاشة منصة واحدة.",
            ["Add restaurant"] = "إضافة مطعم",
            ["Search restaurants"] = "البحث في المطاعم",
            ["Filter by status"] = "تصفية حسب الحالة",
            ["Owner"] = "المالك",
            ["Usage"] = "الاستخدام",
            ["branches"] = "فروع",
            ["menus"] = "قوائم",
            ["products"] = "منتجات",
            ["View owner"] = "عرض المالك",
            ["No restaurants yet"] = "لا توجد مطاعم بعد",
            ["Provision your first restaurant workspace."] = "أنشئ أول مساحة عمل لمطعمك.",
            ["Keep provisioning short; the restaurant owner builds the operational catalog."] = "اجعل الإنشاء مختصراً؛ مالك المطعم يبني الكتالوج التشغيلي.",
            ["Unassigned"] = "غير مُعيّن",
            ["No owner email"] = "لا يوجد بريد للمالك",
            ["Platform restaurant"] = "مطعم على المنصة",
            ["Back to restaurants"] = "العودة إلى المطاعم",
            ["Operational branches"] = "الفروع التشغيلية",
            ["Saved menus"] = "القوائم المحفوظة",
            ["Saved products"] = "المنتجات المحفوظة",
            ["Access"] = "الوصول",
            ["Owner membership"] = "عضوية المالك",
            ["The owner is assigned to this restaurant with the TenantOwner role. Operational setup remains in the tenant workspace."] = "تم تعيين المالك لهذا المطعم بدور مالك المطعم. يبقى الإعداد التشغيلي داخل مساحة عمل المطعم.",
            ["Lifecycle"] = "دورة الحياة",
            ["No subscription history found."] = "لم يتم العثور على سجل اشتراكات.",
            ["Restaurant is operational"] = "المطعم متاح للتشغيل",
            ["Restaurant access is paused"] = "تم إيقاف الوصول إلى المطعم",
            ["Owner access is available according to membership and plan rules."] = "يتاح وصول المالك وفقاً لقواعد العضوية والخطة.",
            ["Owner access is blocked until the platform reactivates this restaurant."] = "تم حظر وصول المالك حتى تعيد المنصة تفعيل المطعم.",
            ["Deactivate restaurant"] = "إيقاف المطعم",
            ["Activate restaurant"] = "تفعيل المطعم",
            ["Pause access for this restaurant?"] = "إيقاف الوصول إلى هذا المطعم؟",
            ["Restore access for this restaurant?"] = "استعادة الوصول إلى هذا المطعم؟",
            ["Short provisioning"] = "إنشاء مختصر",
            ["Restaurant identity, owner access, and plan are all this step requires."] = "تتطلب هذه الخطوة هوية المطعم ووصول المالك والخطة فقط.",
            ["Restaurant information"] = "معلومات المطعم",
            ["The workspace starts operationally empty by design."] = "تبدأ مساحة العمل فارغة تشغيلياً عن قصد.",
            ["Owner access"] = "وصول المالك",
            ["Use an existing registered email to assign that user, or set a secure initial password for a new owner."] = "استخدم بريداً مسجلاً لتعيين مستخدم موجود، أو عيّن كلمة مرور أولية آمنة لمالك جديد.",
            ["Required only for a new owner; at least 10 characters with upper/lowercase, a number, and a symbol."] = "مطلوبة للمالك الجديد فقط؛ 10 أحرف على الأقل مع أحرف كبيرة وصغيرة ورقم ورمز.",
            ["Commercial defaults"] = "الإعدادات التجارية الافتراضية",
            ["The selected plan controls entitlements inside the restaurant workspace."] = "تتحكم الخطة المحددة في الاستحقاقات داخل مساحة عمل المطعم.",
            ["Select plan"] = "اختر الخطة",
            ["Create restaurant"] = "إنشاء المطعم",
            ["Welcome to your restaurant"] = "مرحباً بك في مطعمك",
            ["Your workspace is intentionally empty. Use the setup guidance when useful, or open any restaurant module from the sidebar."] = "مساحة عملك فارغة عن قصد. استخدم إرشادات الإعداد عند الحاجة أو افتح أي وحدة من الشريط الجانبي.",
            ["Continue setup"] = "متابعة الإعداد",
            ["Explore workspace"] = "استكشاف مساحة العمل",
            ["Next action"] = "الإجراء التالي",
            ["Locations in this workspace"] = "المواقع في مساحة العمل",
            ["Menu experiences managed"] = "تجارب القوائم المُدارة",
            ["Products across menus"] = "المنتجات عبر القوائم",
            ["Live guest entry points"] = "نقاط دخول الضيوف النشطة",
            ["A calm view of the restaurant workspace, publishing readiness, and guest signals."] = "نظرة هادئة على مساحة عمل المطعم وجاهزية النشر وإشارات الضيوف.",
            ["Role"] = "الدور",
            ["Operational attention"] = "تنبيهات التشغيل",
            ["Keep the guest experience healthy"] = "حافظ على تجربة ضيف مستقرة",
            ["These live signals are based on the current restaurant workspace."] = "تعتمد هذه الإشارات المباشرة على مساحة عمل المطعم الحالية.",
            ["Open"] = "فتح",
            ["Recent activity"] = "النشاط الأخير",
            ["What changed recently"] = "ما الذي تغير مؤخراً",
            ["Open audit"] = "فتح سجل التدقيق",
            ["System"] = "النظام",
            ["Publishing"] = "النشر",
            ["Guest entry point"] = "نقطة دخول الضيوف",
            ["Orders"] = "الطلبات",
            ["Menu drafts"] = "مسودات القوائم",
            ["Availability"] = "التوفر",
            ["Product media"] = "وسائط المنتجات",
            ["Publish your guest menu"] = "انشر قائمة الضيوف",
            ["Create a guest entry point"] = "أنشئ نقطة دخول للضيوف",
            ["Orders need attention"] = "توجد طلبات تحتاج إلى متابعة",
            ["Draft menus are waiting"] = "توجد قوائم مسودة قيد الانتظار",
            ["Unavailable products"] = "منتجات غير متاحة",
            ["Product images are incomplete"] = "صور المنتجات غير مكتملة",
            ["Branch limit reached"] = "تم بلوغ حد الفروع",
            ["Product limit reached"] = "تم بلوغ حد المنتجات",
            ["User limit reached"] = "تم بلوغ حد المستخدمين",
            ["Order received"] = "تم استلام طلب",
            ["Order status changed"] = "تغيرت حالة الطلب",
            ["Branch created"] = "تم إنشاء فرع",
            ["Branch updated"] = "تم تحديث فرع",
            ["Menu created"] = "تم إنشاء قائمة",
            ["Menu updated"] = "تم تحديث قائمة",
            ["Category created"] = "تم إنشاء فئة",
            ["Category updated"] = "تم تحديث فئة",
            ["Product created"] = "تم إنشاء منتج",
            ["Product updated"] = "تم تحديث منتج",
            ["Restaurant settings updated"] = "تم تحديث إعدادات المطعم",
            ["Payment initiated"] = "بدأت عملية دفع",
            ["Workspace activity"] = "نشاط مساحة العمل",
            ["Commercial workspace"] = "مساحة العمل التجارية",
            ["Plans & billing"] = "الخطط والفوترة",
            ["Database-backed plans, entitlements, subscriptions, and payment history."] = "خطط واستحقاقات واشتراكات وسجل مدفوعات مرتبطة بقاعدة البيانات.",
            ["Current usage"] = "الاستخدام الحالي",
            ["Limits are enforced server-side before a new record is created."] = "تُطبّق الحدود من الخادم قبل إنشاء أي سجل جديد.",
            ["Unlimited"] = "غير محدود",
            ["month"] = "شهر",
            ["Current plan"] = "الخطة الحالية",
            ["Active"] = "نشطة",
            ["Plan limit reached"] = "تم بلوغ حد الخطة",
            ["Review plans"] = "مراجعة الخطط",
            ["Custom branding is not included in the current plan."] = "التخصيصات البصرية المخصصة غير مضمنة في الخطة الحالية.",
            ["No branches yet"] = "لا توجد فروع بعد",
            ["Create your first branch"] = "أنشئ فرعك الأول",
            ["Create your first branch to start assigning menus and publishing your restaurant experience."] = "أنشئ فرعك الأول لبدء تعيين القوائم ونشر تجربة مطعمك.",
            ["Create your first menu"] = "أنشئ قائمتك الأولى",
            ["Create your first menu and start building your restaurant catalog."] = "أنشئ قائمتك الأولى وابدأ في بناء كتالوج مطعمك.",
            ["No products yet"] = "لا توجد منتجات بعد",
            ["Add your first product"] = "أضف منتجك الأول",
            ["Add your first product from a menu category to start building your menu."] = "أضف منتجك الأول من فئة داخل قائمة لبدء بناء قائمتك.",
            ["Open menu studio"] = "فتح استوديو القوائم",
            ["Security"] = "الأمان",
            ["Sign out"] = "تسجيل الخروج",
            ["Open navigation"] = "فتح التنقل",
            ["Close navigation"] = "إغلاق التنقل",
            ["Collapse sidebar"] = "طي الشريط الجانبي",
            ["Expand sidebar"] = "توسيع الشريط الجانبي",
            ["Switch to Arabic"] = "العربية",
            ["Switch to English"] = "الإنجليزية",
            ["Language"] = "اللغة",
            ["Home"] = "الرئيسية",
            ["Sign in"] = "تسجيل الدخول",
            ["Hospitality, thoughtfully managed."] = "ضيافة تُدار بعناية.",
            ["Private workspace"] = "مساحة عمل خاصة",
            ["Welcome back."] = "مرحباً بعودتك.",
            ["Sign in to manage your restaurant menus and branches."] = "سجّل الدخول لإدارة قوائم مطعمك وفروعه.",
            ["Email"] = "البريد الإلكتروني",
            ["Password"] = "كلمة المرور",
            ["Forgot password?"] = "هل نسيت كلمة المرور؟",
            ["Account recovery"] = "استعادة الحساب",
            ["Reset your password."] = "إعادة تعيين كلمة المرور.",
            ["Choose a new password."] = "اختر كلمة مرور جديدة.",
            ["Check your email."] = "تحقق من بريدك الإلكتروني.",
            ["Request reset"] = "طلب إعادة التعيين",
            ["Set new password"] = "تعيين كلمة مرور جديدة",
            ["Return to sign in"] = "العودة إلى تسجيل الدخول",
            ["Invalid credentials"] = "بيانات الدخول غير صحيحة",
            ["The email or password is incorrect."] = "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
            ["Access denied"] = "الوصول مرفوض",
            ["You do not have permission to access this page."] = "ليس لديك صلاحية الوصول إلى هذه الصفحة.",
            ["Error"] = "خطأ",
            ["Success"] = "\u0646\u062c\u062d\u062a \u0627\u0644\u0639\u0645\u0644\u064a\u0629",
            ["Warning"] = "\u062a\u0646\u0628\u064a\u0647",
            ["Info"] = "\u0645\u0639\u0644\u0648\u0645\u0629",
            ["Please correct this field."] = "\u064a\u0631\u062c\u0649 \u062a\u0635\u062d\u064a\u062d \u0647\u0630\u0627 \u0627\u0644\u062d\u0642\u0644.",
            ["Image deleted."] = "\u062a\u0645 \u062d\u0630\u0641 \u0627\u0644\u0635\u0648\u0631\u0629.",
            ["Image replaced."] = "\u062a\u0645 \u0627\u0633\u062a\u0628\u062f\u0627\u0644 \u0627\u0644\u0635\u0648\u0631\u0629.",
            ["Primary image updated."] = "\u062a\u0645 \u062a\u062d\u062f\u064a\u062b \u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0631\u0626\u064a\u0633\u064a\u0629.",
            ["Image order updated."] = "\u062a\u0645 \u062a\u062d\u062f\u064a\u062b \u062a\u0631\u062a\u064a\u0628 \u0627\u0644\u0635\u0648\u0631.",
            ["Restaurant logo deleted."] = "\u062a\u0645 \u062d\u0630\u0641 \u0634\u0639\u0627\u0631 \u0627\u0644\u0645\u0637\u0639\u0645.",
            ["Restaurant cover deleted."] = "\u062a\u0645 \u062d\u0630\u0641 \u063a\u0644\u0627\u0641 \u0627\u0644\u0645\u0637\u0639\u0645.",
            ["Restaurant settings saved; image changes need attention."] = "\u062a\u0645 \u062d\u0641\u0638 \u0625\u0639\u062f\u0627\u062f\u0627\u062a \u0627\u0644\u0645\u0637\u0639\u0645\u060c \u0648\u062a\u062d\u062a\u0627\u062c \u062a\u063a\u064a\u064a\u0631\u0627\u062a \u0627\u0644\u0635\u0648\u0631 \u0625\u0644\u0649 \u0645\u0631\u0627\u062c\u0639\u0629.",
            ["Choose an image file."] = "\u0627\u062e\u062a\u0631 \u0645\u0644\u0641 \u0635\u0648\u0631\u0629.",
            ["Choose a replacement image file."] = "\u0627\u062e\u062a\u0631 \u0645\u0644\u0641 \u0635\u0648\u0631\u0629 \u0628\u062f\u064a\u0644\u0629.",
            ["This file type is not supported. Use JPEG, PNG, or WebP."] = "\u0646\u0648\u0639 \u0627\u0644\u0645\u0644\u0641 \u063a\u064a\u0631 \u0645\u062f\u0639\u0648\u0645. \u0627\u0633\u062a\u062e\u062f\u0645 JPEG \u0623\u0648 PNG \u0623\u0648 WebP.",
            ["The uploaded image size is invalid or the file is empty."] = "\u062d\u062c\u0645 \u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u0645\u0631\u0641\u0648\u0639\u0629 \u063a\u064a\u0631 \u0635\u0627\u0644\u062d \u0623\u0648 \u0623\u0646 \u0627\u0644\u0645\u0644\u0641 \u0641\u0627\u0631\u063a.",
            ["The image file could not be processed because it is corrupted or not a valid image."] = "\u062a\u0639\u0630\u0631 \u062a\u0645\u0631\u064a\u0631 \u0645\u0644\u0641 \u0627\u0644\u0635\u0648\u0631\u0629 \u0644\u0623\u0646\u0647 \u062a\u0627\u0644\u0641 \u0623\u0648 \u0644\u064a\u0633 \u0635\u0648\u0631\u0629 \u0635\u0627\u0644\u062d\u0629.",
            ["Managed product images are maintained in the gallery below. External image URLs are not accepted."] = "\u062a\u062a\u0645 \u0625\u062f\u0627\u0631\u0629 \u0635\u0648\u0631 \u0627\u0644\u0645\u0646\u062a\u062c \u0641\u064a \u0627\u0644\u0645\u0639\u0631\u0636 \u0623\u062f\u0646\u0627\u0647. \u0644\u0627 \u064a\u0645\u0643\u0646 \u0627\u0633\u062a\u062e\u062f\u0627\u0645 \u0631\u0648\u0627\u0628\u0637 \u0635\u0648\u0631 \u062e\u0627\u0631\u062c\u064a\u0629.",
            ["Product images are uploaded from the product editor after creation. External image URLs are not accepted for managed product media."] = "\u062a\u064f\u0631\u0641\u0639 \u0635\u0648\u0631 \u0627\u0644\u0645\u0646\u062a\u062c \u0645\u0646 \u0645\u062d\u0631\u0631 \u0627\u0644\u0645\u0646\u062a\u062c \u0628\u0639\u062f \u0625\u0646\u0634\u0627\u0626\u0647. \u0644\u0627 \u062a\u064f\u0642\u0628\u0644 \u0631\u0648\u0627\u0628\u0637 \u0627\u0644\u0635\u0648\u0631 \u0627\u0644\u062e\u0627\u0631\u062c\u064a\u0629 \u0644\u0644\u0648\u0633\u0627\u0626\u0637 \u0627\u0644\u0645\u062f\u0627\u0631\u0629.",
            ["Upload a real image file for the logo or cover. Files are stored in managed tenant media."] = "\u0627\u0631\u0641\u0639 \u0645\u0644\u0641 \u0635\u0648\u0631\u0629 \u062d\u0642\u064a\u0642\u064a\u0629 \u0644\u0644\u0634\u0639\u0627\u0631 \u0623\u0648 \u0627\u0644\u063a\u0644\u0627\u0641. \u062a\u064f\u062e\u0632\u0646 \u0627\u0644\u0645\u0644\u0641\u0627\u062a \u0641\u064a \u0648\u0633\u0627\u0626\u0637 \u0627\u0644\u0645\u0633\u062a\u0623\u062c\u0631 \u0627\u0644\u0645\u062f\u0627\u0631\u0629.",
            ["User membership created."] = "\u062a\u0645 \u0625\u0646\u0634\u0627\u0621 \u0639\u0636\u0648\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645.",
            ["User membership updated."] = "\u062a\u0645 \u062a\u062d\u062f\u064a\u062b \u0639\u0636\u0648\u064a\u0629 \u0627\u0644\u0645\u0633\u062a\u062e\u062f\u0645.",
            ["Membership activated."] = "\u062a\u0645 \u062a\u0641\u0639\u064a\u0644 \u0627\u0644\u0639\u0636\u0648\u064a\u0629.",
            ["Membership deactivated."] = "\u062a\u0645 \u0625\u0644\u063a\u0627\u0621 \u062a\u0641\u0639\u064a\u0644 \u0627\u0644\u0639\u0636\u0648\u064a\u0629.",
            ["Restaurant settings updated."] = "\u062a\u0645 \u062a\u062d\u062f\u064a\u062b \u0625\u0639\u062f\u0627\u062f\u0627\u062a \u0627\u0644\u0645\u0637\u0639\u0645.",
            ["The current subscription was cancelled."] = "\u062a\u0645 \u0625\u0644\u063a\u0627\u0621 \u0627\u0644\u0627\u0634\u062a\u0631\u0627\u0643 \u0627\u0644\u062d\u0627\u0644\u064a.",
            ["No active subscription was found."] = "\u0644\u0645 \u064a\u062a\u0645 \u0627\u0644\u0639\u062b\u0648\u0631 \u0639\u0644\u0649 \u0627\u0634\u062a\u0631\u0627\u0643 \u0646\u0634\u0637.",
            ["Return home"] = "العودة إلى الرئيسية",
            ["Save"] = "حفظ",
            ["Save changes"] = "حفظ التغييرات",
            ["Cancel"] = "إلغاء",
            ["Confirm"] = "تأكيد",
            ["Confirmation"] = "تأكيد",
            ["Delete"] = "حذف",
            ["Edit"] = "تعديل",
            ["Open"] = "فتح",
            ["Open editor"] = "فتح المحرر",
            ["Copied"] = "تم النسخ",
            ["View"] = "عرض",
            ["Create"] = "إنشاء",
            ["Add"] = "إضافة",
            ["Search"] = "بحث",
            ["Clear"] = "مسح",
            ["Apply"] = "تطبيق",
            ["Apply filters"] = "تطبيق المرشحات",
            ["Actions"] = "الإجراءات",
            ["Type"] = "النوع",
            ["Code"] = "الرمز",
            ["Status"] = "الحالة",
            ["All statuses"] = "كل الحالات",
            ["Active"] = "نشط",
            ["Inactive"] = "غير نشط",
            ["Activate"] = "تفعيل",
            ["Deactivate"] = "إلغاء التفعيل",
            ["Available"] = "متوفر",
            ["Unavailable"] = "غير متوفر",
            ["Visible"] = "مرئي",
            ["Hidden"] = "مخفي",
            ["Published"] = "منشور",
            ["Draft"] = "مسودة",
            ["Archived"] = "مؤرشف",
            ["All branches"] = "كل الفروع",
            ["All branches / not applicable"] = "كل الفروع / لا ينطبق",
            ["All menus"] = "كل القوائم",
            ["All categories"] = "كل الفئات",
            ["All availability"] = "كل حالات التوفر",
            ["Name"] = "الاسم",
            ["English name"] = "الاسم بالإنجليزية",
            ["Arabic name"] = "الاسم بالعربية",
            ["English description"] = "الوصف بالإنجليزية",
            ["Arabic description"] = "الوصف بالعربية",
            ["Description"] = "الوصف",
            ["Price"] = "السعر",
            ["Currency"] = "العملة",
            ["Address"] = "العنوان",
            ["Phone"] = "الهاتف",
            ["Opening hours"] = "ساعات العمل",
            ["Location"] = "الموقع",
            ["Role"] = "الدور",
            ["Branch scope"] = "نطاق الفرع",
            ["Required"] = "مطلوب",
            ["Optional"] = "اختياري",
            ["Product editor"] = "محرر المنتج",
            ["Basic information"] = "المعلومات الأساسية",
            ["Category & classification"] = "الفئة والتصنيف",
            ["Product pricing"] = "تسعير المنتج",
            ["Product images"] = "صور المنتج",
            ["Product ingredients"] = "مكونات المنتج",
            ["Product allergens"] = "مسببات حساسية المنتج",
            ["Product modifiers"] = "إضافات المنتج",
            ["Availability"] = "التوفر",
            ["Branch availability"] = "التوفر حسب الفرع",
            ["History"] = "السجل",
            ["Save product"] = "حفظ المنتج",
            ["Images gallery"] = "معرض الصور",
            ["Upload selected images"] = "رفع الصور المحددة",
            ["Close image"] = "إغلاق الصورة",
            ["Current category"] = "الفئة الحالية",
            ["Product type"] = "نوع المنتج",
            ["Select product type"] = "اختر نوع المنتج",
            ["Select currency"] = "اختر العملة",
            ["Display order"] = "ترتيب العرض",
            ["Make primary"] = "تعيين كصورة رئيسية",
            ["Move up"] = "نقل لأعلى",
            ["Move down"] = "نقل لأسفل",
            ["Replace"] = "استبدال",
            ["Price override"] = "تعديل سعر",
            ["Basic"] = "الأساسي",
            ["Classification"] = "التصنيف",
            ["Gallery"] = "المعرض",
            ["Restaurant identity"] = "هوية المطعم",
            ["Restaurant settings"] = "إعدادات المطعم",
            ["Branch details"] = "تفاصيل الفرع",
            ["Permanent address"] = "العنوان الدائم",
            ["Brand override"] = "تخصيص العلامة التجارية",
            ["Inherited"] = "موروث",
            ["Not provided"] = "غير متوفر",
            ["People & access"] = "الأشخاص والوصول",
            ["Manage tenant memberships and branch scope."] = "إدارة عضويات المستأجر ونطاق الفروع.",
            ["Add user"] = "إضافة مستخدم",
            ["Tenant admin"] = "مسؤول المستأجر",
            ["Branch manager"] = "مدير فرع",
            ["Menu editor"] = "محرر القوائم",
            ["Viewer"] = "مشاهد",
            ["Create membership"] = "إنشاء عضوية",
            ["No memberships found."] = "لم يتم العثور على عضويات.",
            ["Add a user or change the search."] = "أضف مستخدماً أو غيّر البحث.",
            ["Menu studio"] = "استوديو القوائم",
            ["Create menu"] = "إنشاء قائمة",
            ["No menus yet"] = "لا توجد قوائم بعد",
            ["Start your first menu."] = "ابدأ قائمتك الأولى.",
            ["Create a menu, add categories, then build your items."] = "أنشئ قائمة، وأضف الفئات، ثم أنشئ منتجاتك.",
            ["Type / scope"] = "النوع / النطاق",
            ["Open audit history"] = "فتح سجل التدقيق",
            ["Add allergen"] = "إضافة مسبب حساسية",
            ["Add ingredient"] = "إضافة مكوّن",
            ["Add modifier"] = "إضافة إضافة",
            ["No allergens found"] = "لم يتم العثور على مسببات حساسية",
            ["No ingredients found"] = "لم يتم العثور على مكونات",
            ["No matching products"] = "لم يتم العثور على منتجات مطابقة",
            ["No matching branches"] = "لم يتم العثور على فروع مطابقة",
            ["No activity yet"] = "لا يوجد نشاط بعد",
            ["Changes will appear here."] = "ستظهر التغييرات هنا.",
            ["Search name or email"] = "ابحث بالاسم أو البريد الإلكتروني",
            ["Search products"] = "بحث في المنتجات",
            ["Search branches"] = "بحث في الفروع",
            ["Search allergens"] = "بحث في مسببات الحساسية",
            ["Search ingredients"] = "بحث في المكونات",
            ["Search modifier groups"] = "بحث في مجموعات الإضافات",
            ["Add branch"] = "إضافة فرع",
            ["Add a branch"] = "إضافة فرع",
            ["Create branch"] = "إنشاء فرع",
            ["Edit branch"] = "تعديل الفرع",
            ["Create item"] = "إنشاء منتج",
            ["Add a menu item"] = "إضافة منتج للقائمة",
            ["Add category"] = "إضافة فئة",
            ["Create category"] = "إنشاء فئة",
            ["Edit category"] = "تعديل الفئة",
            ["Add lookup value"] = "إضافة قيمة مرجعية",
            ["Edit lookup value"] = "تعديل القيمة المرجعية",
            ["Configuration center"] = "مركز الإعدادات",
            ["Lookup value"] = "القيمة المرجعية",
            ["Lookup type"] = "نوع القائمة المرجعية",
            ["Select an active lookup type"] = "اختر نوع قائمة مرجعية نشطاً",
            ["Back to values"] = "العودة إلى القيم",
            ["Global platform value"] = "قيمة عامة للمنصة",
            ["This value is visible to tenants but can only be changed by the platform owner."] = "هذه القيمة مرئية للمستأجرين ولا يمكن تغييرها إلا بواسطة مالك المنصة.",
            ["Commercial controls"] = "الضوابط التجارية",
            ["Pricing management"] = "إدارة التسعير",
            ["Scope"] = "النطاق",
            ["Operation"] = "العملية",
            ["Value"] = "القيمة",
            ["Reason"] = "السبب",
            ["Choose products"] = "اختيار المنتجات",
            ["Current price"] = "السعر الحالي",
            ["Preview pricing change"] = "معاينة تغيير السعر",
            ["Confirmation required"] = "التأكيد مطلوب",
            ["Review before applying"] = "راجع قبل التطبيق",
            ["Confirm and apply atomically"] = "تأكيد وتطبيق بشكل ذري",
            ["Traceability"] = "التتبع",
            ["Price history"] = "سجل الأسعار",
            ["Commercial workspace"] = "المساحة التجارية",
            ["Plans & billing"] = "الخطط والفوترة",
            ["Current subscription"] = "الاشتراك الحالي",
            ["Cancel subscription"] = "إلغاء الاشتراك",
            ["Plan catalog"] = "كتالوج الخطط",
            ["Plans"] = "الخطط",
            ["Choose plan"] = "اختيار الخطة",
            ["Subscription history"] = "سجل الاشتراكات",
            ["Payments"] = "المدفوعات",
            ["No subscription is assigned."] = "لم يتم تعيين اشتراك.",
            ["No subscription history."] = "لا يوجد سجل اشتراكات.",
            ["No payments recorded."] = "لا توجد مدفوعات مسجلة.",
            ["Governance"] = "الحوكمة",
            ["Audit log"] = "سجل التدقيق",
            ["A tenant-scoped record of meaningful workspace changes."] = "سجل خاص بالمستأجر للتغييرات المهمة في مساحة العمل.",
            ["Guest signals"] = "إشارات الزوار",
            ["Most viewed items"] = "المنتجات الأكثر مشاهدة",
            ["Branch comparison"] = "مقارنة الفروع",
            ["Total scans"] = "إجمالي عمليات المسح",
            ["Today's scans"] = "عمليات المسح اليوم",
            ["No views yet"] = "لا توجد مشاهدات بعد",
            ["Workspace setup"] = "إعداد مساحة العمل",
            ["Your restaurant is ready"] = "مطعمك جاهز",
            ["Keep building your restaurant"] = "واصل بناء مطعمك",
            ["Review restaurant"] = "مراجعة المطعم",
            ["Restaurant setup"] = "إعداد المطعم",
            ["Continue from the next saved business step. Progress reflects database state."] = "تابع من الخطوة التجارية المحفوظة التالية. يعكس التقدم حالة قاعدة البيانات.",
            ["Complete restaurant identity"] = "استكمال هوية المطعم",
            ["Review the restaurant settings before building the guest experience."] = "راجع إعدادات المطعم قبل بناء تجربة الضيوف.",
            ["Branches are saved independently and can be added whenever your restaurant grows."] = "تُحفظ الفروع بشكل مستقل ويمكن إضافتها كلما نما مطعمك.",
            ["Create a menu before adding categories and products to it."] = "أنشئ قائمة قبل إضافة الفئات والمنتجات إليها.",
            ["Organize the menu into categories before adding products."] = "نظّم القائمة إلى فئات قبل إضافة المنتجات.",
            ["Add a product inside a menu category, then enrich its content separately."] = "أضف منتجاً داخل فئة قائمة ثم أكمل محتواه بشكل مستقل.",
            ["Preview the saved menu and publish it when the guest experience is ready."] = "عاين القائمة المحفوظة وانشرها عندما تصبح تجربة الضيوف جاهزة.",
            ["Create a QR code so guests can enter the published experience."] = "أنشئ رمز QR ليتمكن الضيوف من الوصول إلى التجربة المنشورة.",
            ["Use the workspace shortcuts below to manage the live experience."] = "استخدم اختصارات مساحة العمل أدناه لإدارة التجربة المنشورة.",
            ["Create your first category"] = "أنشئ فئتك الأولى",
            ["Preview and publish your menu"] = "عاين قائمتك وانشرها",
            ["Create your first QR code"] = "أنشئ رمز QR الأول",
            ["Your restaurant is ready for daily management"] = "مطعمك جاهز للإدارة اليومية",
            ["Create menu"] = "إنشاء قائمة",
            ["Categories"] = "الفئات",
            ["Preview"] = "معاينة",
            ["Publish"] = "نشر",
            ["Open menus"] = "فتح القوائم",
            ["Open products"] = "فتح المنتجات",
            ["Create QR code"] = "إنشاء رمز QR",
            ["Explore workspace"] = "استكشاف مساحة العمل",
            ["Configure identity"] = "إعداد الهوية",
            ["Create a menu"] = "إنشاء قائمة",
            ["Add a category"] = "إضافة فئة",
            ["Add a product"] = "إضافة منتج",
            ["Publish when ready"] = "النشر عند الجاهزية",
            ["Create a guest entry point"] = "إنشاء نقطة دخول للضيوف",
            ["Ready"] = "جاهز",
            ["Accepted"] = "مقبول",
            ["Preparing"] = "قيد التحضير",
            ["Completed"] = "مكتمل",
            ["Rejected"] = "مرفوض",
            ["Cancelled"] = "ملغي",
            ["Tables"] = "الطاولات",
            ["Complete"] = "مكتمل",
            ["First branch"] = "الفرع الأول",
            ["Starter menu"] = "القائمة الأساسية",
            ["Publish menu"] = "نشر القائمة",
            ["Analytics is not included"] = "التحليلات غير مشمولة",
            ["Upgrade the current plan to unlock advanced analytics."] = "رقِّ الخطة الحالية لفتح التحليلات المتقدمة.",
            ["View plans"] = "عرض الخطط",
            ["Currently unavailable"] = "غير متوفر حالياً",
            ["There are no items in this menu right now."] = "لا توجد منتجات في هذه القائمة حالياً.",
            ["Product image"] = "صورة المنتج",
            ["View image"] = "عرض الصورة",
            ["Close"] = "إغلاق",
            ["Category"] = "الفئة",
            ["Subcategory"] = "فئة فرعية",
            ["Contains"] = "يحتوي على",
            ["Options"] = "الخيارات",
            ["English"] = "الإنجليزية",
            ["Arabic"] = "العربية",
            ["Previous"] = "السابق",
            ["Next"] = "التالي",
            ["First"] = "الأول",
            ["Last"] = "الأخير",
            ["Page"] = "صفحة",
            ["No records found"] = "لم يتم العثور على سجلات",
            ["Loading..."] = "جارٍ التحميل...",
            ["Something went wrong"] = "حدث خطأ ما",
            ["Please try again"] = "يرجى المحاولة مرة أخرى",
            ["Saved successfully"] = "تم الحفظ بنجاح",
            ["Deleted successfully"] = "تم الحذف بنجاح",
            ["Updated successfully"] = "تم التحديث بنجاح",
            ["Published successfully"] = "تم النشر بنجاح",
            ["TenantOwner"] = "مالك المستأجر",
            ["TenantAdmin"] = "مسؤول المستأجر",
            ["BranchManager"] = "مدير فرع",
            ["MenuEditor"] = "محرر القوائم",
            ["PlatformAdmin"] = "مسؤول المنصة",
            ["Trial"] = "تجريبي",
            ["Pending"] = "قيد الانتظار",
            ["Paid"] = "مدفوع",
            ["Failed"] = "فشل",
            ["Unlimited"] = "غير محدود",
            ["Global"] = "عام",
            ["system"] = "النظام",
            ["The Email field is required."] = "حقل البريد الإلكتروني مطلوب.",
            ["The Password field is required."] = "حقل كلمة المرور مطلوب.",
            ["The Email field is not a valid e-mail address."] = "حقل البريد الإلكتروني ليس عنوان بريد صالحاً.",
            ["The Email field is not a valid email address."] = "حقل البريد الإلكتروني ليس عنوان بريد صالحاً.",
            ["The Token field is required."] = "حقل الرمز مطلوب.",
            ["The New password field is required."] = "حقل كلمة المرور الجديدة مطلوب.",
            ["The Confirm password field is required."] = "حقل تأكيد كلمة المرور مطلوب.",
            ["The Name field is required."] = "حقل الاسم مطلوب.",
            ["The Price field is required."] = "حقل السعر مطلوب.",
            ["The field Email must be a valid email address."] = "يجب أن يكون حقل البريد الإلكتروني عنوان بريد صالحاً.",
            ["Use a six-digit hex color."] = "استخدم لوناً سداسياً مكوناً من ستة أرقام.",
            ["Use lowercase letters, numbers, and hyphens."] = "استخدم الأحرف الصغيرة والأرقام والواصلات فقط.",
            ["Trial · Active entitlement"] = "تجريبي · اشتراك نشط",
            ["Restaurant Menu Platform"] = "منصة قوائم المطاعم",
            ["MenuPlatform"] = "منصة القوائم",
            ["Development Admin"] = "مسؤول التطوير",
            ["Demo Restaurant"] = "المطعم التجريبي",
            ["Manage the bilingual identity and public-facing defaults for this tenant."] = "إدارة هوية المستأجر الثنائية اللغة والإعدادات الافتراضية الظاهرة للجمهور.",
            ["Search, filter, and maintain every location."] = "ابحث عن كل موقع، وصفّه، وأدره.",
            ["Shape the menu your guests see, one detail at a time."] = "صمّم القائمة التي يراها ضيوفك، تفصيلاً بعد آخر.",
            ["Product catalog"] = "كتالوج المنتجات",
            ["Search, filter, and maintain the products shared by your menus."] = "ابحث عن المنتجات المشتركة بين قوائمك وصفّها وأدرها.",
            ["Menu data"] = "بيانات القائمة",
            ["Ingredients & allergens"] = "المكونات ومسببات الحساسية",
            ["Manage reusable ingredient records and allergen declarations for this tenant."] = "إدارة سجلات المكونات القابلة لإعادة الاستخدام وإقرارات مسببات الحساسية لهذا المستأجر.",
            ["Manage the disclosure vocabulary used by published menus."] = "إدارة مفردات الإفصاح المستخدمة في القوائم المنشورة.",
            ["Menu configuration"] = "إعدادات القائمة",
            ["Manage optional selections and price adjustments for menu products."] = "إدارة الاختيارات الاختيارية وتعديلات الأسعار لمنتجات القائمة.",
            ["Preview an adjustment, confirm it, and keep a complete tenant-scoped history."] = "عاين التعديل وأكّده واحتفظ بسجل كامل خاص بالمستأجر.",
            ["Effective price"] = "السعر الفعلي",
            ["base product price, with a branch override applied when a branch is selected."] = "سعر المنتج الأساسي، مع تطبيق تعديل الفرع عند اختيار فرع.",
            ["Select scope"] = "اختر النطاق",
            ["Individual products"] = "منتجات فردية",
            ["Select operation"] = "اختر العملية",
            ["Percentage increase"] = "زيادة بنسبة مئوية",
            ["Percentage decrease"] = "خفض بنسبة مئوية",
            ["Fixed amount increase"] = "زيادة بمبلغ ثابت",
            ["Fixed amount decrease"] = "خفض بمبلغ ثابت",
            ["Set exact price"] = "تعيين سعر محدد",
            ["For category or branch scope, the server resolves the complete set."] = "بالنسبة لنطاق الفئة أو الفرع، يحدد الخادم المجموعة الكاملة.",
            ["Product / branch"] = "المنتج / الفرع",
            ["Operation / change"] = "العملية / التغيير",
            ["Distribution"] = "التوزيع",
            ["Permanent links resolve the current published menu at scan time."] = "تفتح الروابط الدائمة القائمة المنشورة الحالية وقت المسح.",
            ["Print layout"] = "تنسيق الطباعة",
            ["Load codes"] = "تحميل الرموز",
            ["Table labels (optional"] = "تسميات الطاولات (اختياري",
            ["one per line, comma, or semicolon"] = "واحد في كل سطر أو مفصول بفاصلة أو فاصلة منقوطة",
            ["Leave empty to generate the branch-level QR."] = "اتركه فارغاً لإنشاء رمز QR على مستوى الفرع.",
            ["Labels are operational metadata"] = "التسميات بيانات تشغيلية",
            ["every QR still points to the same stable branch menu route."] = "تبقى جميع رموز QR مرتبطة بمسار قائمة الفرع الثابت نفسه.",
            ["Copy link"] = "نسخ الرابط",
            ["Controlled type definitions keep value forms consistent across the workspace."] = "تحافظ تعريفات الأنواع المضبوطة على اتساق نماذج القيم في مساحة العمل.",
            ["Add type"] = "إضافة نوع",
            ["Descending"] = "تنازلي",
            ["Values"] = "القيم",
            ["Order"] = "الترتيب",
            ["Tenant values are database-backed and used immediately by menu and workspace forms."] = "قيم المستأجر محفوظة في قاعدة البيانات وتُستخدم فوراً في نماذج القائمة ومساحة العمل.",
            ["Add value"] = "إضافة قيمة",
            ["All lookup types"] = "كل أنواع القوائم المرجعية",
            ["Database-backed plans, entitlements, subscriptions, and payment history."] = "خطط واشتراكات واستحقاقات وسجل مدفوعات محفوظة في قاعدة البيانات.",
            ["Plan"] = "الخطة",
            ["Monthly price"] = "السعر الشهري",
            ["Features"] = "الميزات",
            ["Action"] = "الإجراء",
            ["Started"] = "بدأ",
            ["Provider callbacks"] = "استدعاءات مزود الخدمة",
            ["User · login.succeeded"] = "المستخدم · نجاح تسجيل الدخول",
            ["After"] = "بعد",
            ["lastLoginAtUtc"] = "آخر تسجيل دخول",
            ["Account security"] = "أمان الحساب",
            ["Use a unique password with at least 10 characters, uppercase, lowercase, number, and symbol."] = "استخدم كلمة مرور فريدة من 10 أحرف على الأقل، وتحتوي على حرف كبير وصغير ورقم ورمز.",
            ["CurrentPassword"] = "كلمة المرور الحالية",
            ["NewPassword"] = "كلمة المرور الجديدة",
            ["ConfirmPassword"] = "تأكيد كلمة المرور",
            ["Change password"] = "تغيير كلمة المرور",
            ["Logo URL"] = "رابط الشعار",
            ["Cover image URL"] = "رابط صورة الغلاف",
            ["Primary brand color"] = "لون العلامة الأساسي",
            ["Accent brand color"] = "لون العلامة المميز",
            ["Default language"] = "اللغة الافتراضية",
            ["Save restaurant settings"] = "حفظ إعدادات المطعم",
            ["Egyptian pound"] = "الجنيه المصري",
            ["US dollar"] = "الدولار الأمريكي",
            ["Euro"] = "اليورو",
            ["Open editor"] = "فتح المحرر",
            ["No image"] = "لا توجد صورة",
            ["image(s)"] = "صورة/صور",
            ["Mark available"] = "تحديد كمتوفر",
            ["Mark unavailable"] = "تحديد كغير متوفر",
            ["Select products for a bulk availability update."] = "اختر المنتجات لتحديث التوفر بشكل جماعي.",
            ["Unclassified"] = "غير مصنف",
            ["Fixed"] = "ثابت",
            ["Group"] = "المجموعة",
            ["Selection"] = "الاختيار",
            ["New"] = "الجديد",
            ["When"] = "متى",
            ["Change"] = "التغيير",
            ["Actor"] = "المنفذ",
            ["Selected branches"] = "الفروع المحددة",
            ["Top-level category"] = "الفئة الرئيسية",
            ["Select classification"] = "اختر التصنيف",
            ["Select from database"] = "اختر من قاعدة البيانات",
            ["A focused view of how guests are discovering the published experience."] = "نظرة مركزة على كيفية وصول الضيوف إلى التجربة المنشورة.",
            ["Activate table"] = "تفعيل الطاولة",
            ["Activate this table for QR ordering?"] = "هل تريد تفعيل هذه الطاولة للطلب عبر رمز QR؟",
            ["Active QR ready"] = "رمز QR نشط وجاهز",
            ["Add a clear dish photo to make the public menu easier to scan."] = "أضف صورة واضحة للطبق لتسهيل تصفح القائمة العامة.",
            ["Add product"] = "إضافة منتج",
            ["Add your first category."] = "أضف فئتك الأولى.",
            ["All active branches"] = "جميع الفروع النشطة",
            ["All tables"] = "جميع الطاولات",
            ["Allergen filters"] = "عوامل تصفية مسببات الحساسية",
            ["Allergen pages"] = "صفحات مسببات الحساسية",
            ["Alt text for uploaded images"] = "النص البديل للصور المرفوعة",
            ["Arabic table name"] = "اسم الطاولة بالعربية",
            ["Attention"] = "تنبيهات",
            ["Audit history"] = "سجل التدقيق",
            ["Base price"] = "السعر الأساسي",
            ["Base price and currency are saved with this product; advanced adjustments remain in Pricing."] = "يُحفظ السعر الأساسي والعملة مع هذا المنتج، بينما تبقى التعديلات المتقدمة ضمن التسعير.",
            ["Branch assignment"] = "تعيين الفروع",
            ["Branch filters"] = "عوامل تصفية الفروع",
            ["Branch overrides inherit the global product state unless explicitly changed."] = "ترث إعدادات الفرع حالة المنتج العامة ما لم يتم تغييرها صراحةً.",
            ["Breadcrumbs"] = "مسار التنقل",
            ["Categories make a long menu easy to browse."] = "تجعل الفئات تصفح القوائم الطويلة أكثر سهولة.",
            ["Change the shared availability without leaving the editor."] = "غيّر التوفر العام دون مغادرة المحرر.",
            ["Changes to this product and its images are recorded in the tenant audit trail."] = "تُسجل تغييرات هذا المنتج وصوره في سجل تدقيق المستأجر.",
            ["Choose product images"] = "اختر صور المنتج",
            ["Choose subscription plan"] = "اختر خطة الاشتراك",
            ["Configure the modifier groups available for this product."] = "اضبط مجموعات الإضافات المتاحة لهذا المنتج.",
            ["Confirm order status"] = "تأكيد حالة الطلب",
            ["Content"] = "المحتوى",
            ["Content belongs to this product and can be refined independently."] = "ينتمي هذا المحتوى إلى المنتج ويمكن تحسينه بصورة مستقلة.",
            ["Continue to payment"] = "المتابعة إلى الدفع",
            ["Created"] = "تاريخ الإنشاء",
            ["Date from"] = "من تاريخ",
            ["Date to"] = "إلى تاريخ",
            ["Deactivate table"] = "تعطيل الطاولة",
            ["Deactivate this table? Its QR code will no longer accept new orders."] = "هل تريد تعطيل هذه الطاولة؟ لن يقبل رمز QR الخاص بها طلبات جديدة.",
            ["Describe the dish for accessibility"] = "صِف الطبق لدعم إمكانية الوصول",
            ["Edit menu"] = "تعديل القائمة",
            ["Edit table"] = "تعديل الطاولة",
            ["Gallery image"] = "صورة من المعرض",
            ["Generate QR"] = "إنشاء رمز QR",
            ["Global availability"] = "التوفر العام",
            ["Global availability is separate from branch overrides."] = "التوفر العام مستقل عن إعدادات الفروع.",
            ["Guest"] = "الضيف",
            ["Ingredient filters"] = "عوامل تصفية المكونات",
            ["Ingredient pages"] = "صفحات المكونات",
            ["Items"] = "العناصر",
            ["Keep the product identity and classification together."] = "حافظ على هوية المنتج وتصنيفه معًا.",
            ["Keep the product in the correct menu context."] = "أبقِ المنتج ضمن سياق القائمة الصحيح.",
            ["Link copied to clipboard."] = "تم نسخ الرابط إلى الحافظة.",
            ["Load tables"] = "تحميل الطاولات",
            ["Lookup filters"] = "عوامل تصفية القيم المرجعية",
            ["Lookup type filters"] = "عوامل تصفية الأنواع المرجعية",
            ["Lookup type pages"] = "صفحات الأنواع المرجعية",
            ["Menu workspace"] = "مساحة عمل القائمة",
            ["Menu workspace sections"] = "أقسام مساحة عمل القائمة",
            ["Modifier filters"] = "عوامل تصفية الإضافات",
            ["Modifier pages"] = "صفحات الإضافات",
            ["Move to draft"] = "إعادة إلى المسودة",
            ["No active QR"] = "لا يوجد رمز QR نشط",
            ["No active branch is assigned."] = "لم يتم تعيين فرع نشط.",
            ["No alt text"] = "لا يوجد نص بديل",
            ["No images yet"] = "لا توجد صور بعد",
            ["No items in this category yet."] = "لا توجد منتجات في هذه الفئة بعد.",
            ["Not issued"] = "لم يتم الإصدار",
            ["Not recorded"] = "غير مسجل",
            ["Not set"] = "غير محدد",
            ["On the current page"] = "في الصفحة الحالية",
            ["Open QR"] = "فتح رمز QR",
            ["Open editor to add"] = "افتح المحرر للإضافة",
            ["Order filters"] = "عوامل تصفية الطلبات",
            ["Order number, guest, or phone"] = "رقم الطلب أو الضيف أو الهاتف",
            ["Payment is not considered complete until the provider confirms it."] = "لا يُعد الدفع مكتملًا حتى يؤكده مزود الخدمة.",
            ["Primary"] = "رئيسية",
            ["Product catalog summary"] = "ملخص كتالوج المنتجات",
            ["Product changes are recorded in the tenant audit trail."] = "تُسجل تغييرات المنتج في سجل تدقيق المستأجر.",
            ["Product filters"] = "عوامل تصفية المنتجات",
            ["Product image gallery"] = "معرض صور المنتج",
            ["Product pages"] = "صفحات المنتجات",
            ["Product types are tenant lookup values and are not hard-coded in this editor."] = "أنواع المنتجات قيم مرجعية خاصة بالمستأجر وليست ثابتة داخل هذا المحرر.",
            ["Product workspace"] = "مساحة عمل المنتج",
            ["Product workspace sections"] = "أقسام مساحة عمل المنتج",
            ["Provision the workspace and its first owner. Branches, menus, categories, products, pricing, QR, and orders remain the owner's work."] = "أنشئ مساحة العمل ومالكها الأول. تبقى الفروع والقوائم والفئات والمنتجات والتسعير ورموز QR والطلبات ضمن عمل المالك.",
            ["Publication state"] = "حالة النشر",
            ["QR"] = "رمز QR",
            ["QR filters"] = "عوامل تصفية رموز QR",
            ["QR status"] = "حالة رمز QR",
            ["Reset"] = "إعادة ضبط",
            ["Restaurant filters"] = "عوامل تصفية المطاعم",
            ["Save publication state"] = "حفظ حالة النشر",
            ["Search English or Arabic content"] = "ابحث في المحتوى العربي أو الإنجليزي",
            ["Search code, name, or description"] = "ابحث بالرمز أو الاسم أو الوصف",
            ["Search code, type, name, or description"] = "ابحث بالرمز أو النوع أو الاسم أو الوصف",
            ["Search name, slug, or address"] = "ابحث بالاسم أو الرابط أو العنوان",
            ["Select"] = "تحديد",
            ["Select language"] = "اختر اللغة",
            ["Select managed allergen records for public disclosure."] = "حدد سجلات مسببات الحساسية المُدارة لعرضها للضيوف.",
            ["Select managed ingredient records. New ingredients are created in Catalog → Ingredients."] = "حدد سجلات المكونات المُدارة. تُنشأ المكونات الجديدة من الكتالوج ← المكونات.",
            ["Select product type from database"] = "اختر نوع المنتج من قاعدة البيانات",
            ["Sort by"] = "الترتيب حسب",
            ["Start the subscription checkout for"] = "بدء دفع الاشتراك لخطة",
            ["Table"] = "الطاولة",
            ["Table filters"] = "عوامل تصفية الطاولات",
            ["Table name"] = "اسم الطاولة",
            ["This product is not assigned to an active branch through its menu."] = "هذا المنتج غير معيّن إلى فرع نشط من خلال قائمته.",
            ["Total"] = "الإجمالي",
            ["Total products in results"] = "إجمالي المنتجات في النتائج",
            ["Unable to copy link."] = "تعذر نسخ الرابط.",
            ["Unavailable on the current page"] = "غير متاح في الصفحة الحالية",
            ["Under"] = "ضمن",
            ["Upload multiple images, choose a primary image, reorder the gallery, or replace an existing image."] = "ارفع عدة صور، واختر الصورة الرئيسية، وأعد ترتيب المعرض أو استبدل صورة موجودة.",
            ["User filters"] = "عوامل تصفية المستخدمين",
            ["User pages"] = "صفحات المستخدمين",
            ["Which branches use this menu?"] = "ما الفروع التي تستخدم هذه القائمة؟",
            ["at"] = "في",
            ["users"] = "مستخدمون",
            ["Inactive · Reactivate before use"] = "غير نشط · أعد التفعيل قبل الاستخدام",
            ["Print"] = "طباعة",
            ["QR code for"] = "رمز QR لـ",
            ["Table QR codes"] = "رموز QR للطاولات",
            ["Table-specific guest entry points"] = "نقاط دخول الضيوف الخاصة بالطاولات",
        };

    private static readonly string[] PhraseKeys = Arabic.Keys
        .Where(key => key.Contains(' '))
        .OrderByDescending(key => key.Length)
        .ToArray();

    private static readonly string[] TokenKeys = Arabic.Keys
        .Where(key => !key.Contains(' ') && key.Length >= 4)
        .OrderByDescending(key => key.Length)
        .ToArray();

    public static bool IsArabic => string.Equals(
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName,
        "ar",
        StringComparison.OrdinalIgnoreCase);

    public static string Get(string key)
    {
        if (!IsArabic)
            return key;
        return Arabic.TryGetValue(key, out var value) ? value : DashboardArabic(key);
    }

    private static string DashboardArabic(string key) => key switch
    {
        "Restaurant command center" => "\u0644\u0648\u062d\u0629 \u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u0645\u0637\u0639\u0645",
        "Manage branches, menus, products, publishing, and daily readiness." => "\u0625\u062f\u0627\u0631\u0629 \u0641\u0631\u0648\u0639\u0643 \u0648\u0642\u0648\u0627\u0626\u0645\u0643 \u0648\u0645\u0646\u062a\u062c\u0627\u062a\u0643 \u0648\u0646\u0634\u0631\u0647\u0627 \u0648\u0645\u062a\u0627\u0628\u0639\u0629 \u062c\u0627\u0647\u0632\u064a\u0629 \u0627\u0644\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u064a\u0648\u0645\u064a\u0629.",
        "Operational status" => "\u0627\u0644\u062d\u0627\u0644\u0629 \u0627\u0644\u062a\u0634\u063a\u064a\u0644\u064a\u0629",
        "Ready for daily operations" => "\u062c\u0627\u0647\u0632 \u0644\u0644\u062a\u0634\u063a\u064a\u0644 \u0627\u0644\u064a\u0648\u0645\u064a",
        "Setup in progress" => "\u0627\u0644\u0625\u0639\u062f\u0627\u062f \u0642\u064a\u062f \u0627\u0644\u062a\u0646\u0641\u064a\u0630",
        "All core systems are configured and ready for service." => "\u062a\u0645 \u0625\u0639\u062f\u0627\u062f \u0627\u0644\u0623\u0646\u0638\u0645\u0629 \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629 \u0648\u0647\u064a \u062c\u0627\u0647\u0632\u0629 \u0644\u0644\u062a\u0634\u063a\u064a\u0644.",
        "Complete the remaining saved setup steps before service begins." => "\u0623\u0643\u0645\u0644 \u062e\u0637\u0648\u0627\u062a \u0627\u0644\u0625\u0639\u062f\u0627\u062f \u0627\u0644\u0645\u062a\u0628\u0642\u064a\u0629 \u0627\u0644\u0645\u062d\u0641\u0648\u0638\u0629 \u0642\u0628\u0644 \u0628\u062f\u0621 \u0627\u0644\u062a\u0634\u063a\u064a\u0644.",
        "Needs review" => "\u064a\u062d\u062a\u0627\u062c \u0645\u0631\u0627\u062c\u0639\u0629",
        "Needs setup" => "\u064a\u062d\u062a\u0627\u062c \u0625\u0639\u062f\u0627\u062f\u0627\u064b",
        "published" => "\u0645\u0646\u0634\u0648\u0631\u0629",
        "Pending staff action" => "\u0628\u0627\u0646\u062a\u0638\u0627\u0631 \u0625\u062c\u0631\u0627\u0621 \u0627\u0644\u0645\u0648\u0638\u0641\u064a\u0646",
        "Key metrics" => "\u0627\u0644\u0645\u0624\u0634\u0631\u0627\u062a \u0627\u0644\u0623\u0633\u0627\u0633\u064a\u0629",
        "Needs attention" => "\u064a\u062d\u062a\u0627\u062c \u0625\u0644\u0649 \u0627\u0646\u062a\u0628\u0627\u0647\u0643",
        "Quick actions" => "\u0625\u062c\u0631\u0627\u0621\u0627\u062a \u0633\u0631\u064a\u0639\u0629",
        "Workspace shortcuts" => "\u0627\u062e\u062a\u0635\u0627\u0631\u0627\u062a \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644",
        "Review daily operations" => "\u0631\u0627\u062c\u0639 \u0627\u0644\u0639\u0645\u0644\u064a\u0627\u062a \u0627\u0644\u064a\u0648\u0645\u064a\u0629",
        "Review the newest orders and keep service moving." => "\u0631\u0627\u062c\u0639 \u0623\u062d\u062f\u062b \u0627\u0644\u0637\u0644\u0628\u0627\u062a \u0648\u062d\u0627\u0641\u0638 \u0639\u0644\u0649 \u0627\u0633\u062a\u0645\u0631\u0627\u0631 \u0627\u0644\u062e\u062f\u0645\u0629.",
        "Review the live workspace and keep the guest experience current." => "\u0631\u0627\u062c\u0639 \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644 \u0627\u0644\u0646\u0634\u0637\u0629 \u0648\u062d\u0627\u0641\u0638 \u0639\u0644\u0649 \u062a\u062c\u0631\u0628\u0629 \u0627\u0644\u0636\u064a\u0641 \u0645\u062d\u062f\u062b\u0629.",
        "Restaurant health" => "\u0635\u062d\u0629 \u0627\u0644\u0645\u0637\u0639\u0645",
        "Setup is complete. The workspace is ready for ongoing service management." => "\u0627\u0643\u062a\u0645\u0644 \u0627\u0644\u0625\u0639\u062f\u0627\u062f. \u0645\u0633\u0627\u062d\u0629 \u0627\u0644\u0639\u0645\u0644 \u062c\u0627\u0647\u0632\u0629 \u0644\u0625\u062f\u0627\u0631\u0629 \u0627\u0644\u062e\u062f\u0645\u0629 \u0627\u0644\u0645\u0633\u062a\u0645\u0631\u0629.",
        "Action required" => "\u0625\u062c\u0631\u0627\u0621 \u0645\u0637\u0644\u0648\u0628",
        "Guest signals" => "\u0625\u0634\u0627\u0631\u0627\u062a \u0627\u0644\u0636\u064a\u0648\u0641",
        "Total scans" => "\u0625\u062c\u0645\u0627\u0644\u064a \u0627\u0644\u0645\u0633\u062d\u0627\u062a",
        "Today's scans" => "\u0645\u0633\u062d\u0627\u062a \u0627\u0644\u064a\u0648\u0645",
        "Most viewed menu" => "\u0627\u0644\u0642\u0627\u0626\u0645\u0629 \u0627\u0644\u0623\u0643\u062b\u0631 \u0645\u0634\u0627\u0647\u062f\u0629",
        "No views yet" => "\u0644\u0627 \u062a\u0648\u062c\u062f \u0645\u0634\u0627\u0647\u062f\u0627\u062a \u0628\u0639\u062f",
        _ => key
    };

    public static string Feedback(string? message)
    {
        if (string.IsNullOrWhiteSpace(message) || !IsArabic)
            return message ?? string.Empty;

        if (Arabic.TryGetValue(message, out var exact))
            return exact;

        var validation = LocalizeValidation(message);
        if (validation is not null)
            return validation;

        var applied = Regex.Match(message, "^Applied pricing to (?<count>\\d+) product\\(s\\)\\.$", RegexOptions.CultureInvariant);
        if (applied.Success)
            return $"تم تطبيق التسعير على {applied.Groups["count"].Value} منتج/منتجات.";

        var updated = Regex.Match(message, "^(?<count>\\d+) product\\(s\\) updated\\.$", RegexOptions.CultureInvariant);
        if (updated.Success)
            return $"تم تحديث {updated.Groups["count"].Value} منتج/منتجات.";

        var uploaded = Regex.Match(message, "^(?<count>\\d+) image\\(s\\) uploaded\\.$", RegexOptions.CultureInvariant);
        if (uploaded.Success)
            return $"تم رفع {uploaded.Groups["count"].Value} صورة/صور.";

        return message;
    }

    public static string Business(string? fallback, string? english, string? arabic)
    {
        if (IsArabic)
            return string.IsNullOrWhiteSpace(arabic) ? (english ?? fallback ?? string.Empty) : arabic;

        return string.IsNullOrWhiteSpace(english) ? (fallback ?? arabic ?? string.Empty) : english;
    }

    public static string TranslateHtml(string html)
    {
        if (!IsArabic || string.IsNullOrEmpty(html))
            return html;

        return Regex.Replace(
            html,
            "(?s)(<script\\b.*?</script>|<style\\b.*?</style>|<[^>]+>|[^<]+)",
            match => match.Value.StartsWith("<", StringComparison.Ordinal)
                ? TranslateTagAttributes(match.Value)
                : TranslateTextNode(match.Value));
    }

    private static string TranslateTextNode(string text)
    {
        var trimmed = text.Trim();
        if (trimmed.Length == 0)
            return text;

        if (Arabic.TryGetValue(trimmed, out var exact))
            return text.Replace(trimmed, exact, StringComparison.Ordinal);

        var setupMatch = Regex.Match(trimmed, "^(\\d+) of (\\d+) setup steps complete\\.$", RegexOptions.CultureInvariant);
        if (setupMatch.Success)
        {
            var localized = $"اكتمل {setupMatch.Groups[1].Value} من {setupMatch.Groups[2].Value} خطوات الإعداد.";
            return text.Replace(trimmed, localized, StringComparison.Ordinal);
        }

        var imageSize = Regex.Match(trimmed, "^The image exceeds the maximum allowed size of (?<max>\\d+) MB or is empty\\.$", RegexOptions.CultureInvariant);
        if (imageSize.Success)
        {
            var localized = $"\u062a\u062a\u062c\u0627\u0648\u0632 \u0627\u0644\u0635\u0648\u0631\u0629 \u0627\u0644\u062d\u062f \u0627\u0644\u0623\u0642\u0635\u0649 \u0627\u0644\u0645\u0633\u0645\u0648\u062d \u0628\u0647 \u0648\u0647\u0648 {imageSize.Groups["max"].Value} MB \u0623\u0648 \u0623\u0646\u0647\u0627 \u0641\u0627\u0631\u063a\u0629.";
            return text.Replace(trimmed, localized, StringComparison.Ordinal);
        }

        var translated = text;
        foreach (var key in PhraseKeys)
        {
            if (Arabic.TryGetValue(key, out var localized))
                translated = translated.Replace(key, localized, StringComparison.Ordinal);
        }

        foreach (var key in TokenKeys)
        {
            if (!Arabic.TryGetValue(key, out var localized))
                continue;

            translated = Regex.Replace(
                translated,
                $"(?<![\\p{{L}}\\p{{N}}_]){Regex.Escape(key)}(?![\\p{{L}}\\p{{N}}_])",
                localized,
                RegexOptions.CultureInvariant);
        }

        return translated;
    }

    private static string TranslateTagAttributes(string tag)
    {
        if (tag.StartsWith("<script", StringComparison.OrdinalIgnoreCase) ||
            tag.StartsWith("<style", StringComparison.OrdinalIgnoreCase))
            return tag;

        return Regex.Replace(
            tag,
            "(?<name>aria-label|title|placeholder|alt|data-val-[a-z-]+)=(?<quote>[\\\"])(?<value>.*?)(\\k<quote>)",
            match =>
            {
                var value = match.Groups["value"].Value;
                var localized = LocalizeValidation(value);
                return localized is null
                    ? match.Value
                    : $"{match.Groups["name"].Value}={match.Groups["quote"].Value}{localized}{match.Groups["quote"].Value}";
            },
            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
    }

    private static string? LocalizeValidation(string value)
    {
        if (Arabic.TryGetValue(value, out var exact))
            return exact;

        var required = Regex.Match(value, "^The (?<field>.+?) field is required\\.$", RegexOptions.CultureInvariant);
        if (required.Success)
            return $"حقل {LocalizeField(required.Groups["field"].Value)} مطلوب.";

        var length = Regex.Match(value, "^The field (?<field>.+?) must be a string with a minimum length of (?<min>\\d+) and a maximum length of (?<max>\\d+)\\.$", RegexOptions.CultureInvariant);
        if (length.Success)
            return $"يجب أن يكون حقل {LocalizeField(length.Groups["field"].Value)} نصاً بطول لا يقل عن {length.Groups["min"].Value} ولا يزيد عن {length.Groups["max"].Value}.";

        var compare = Regex.Match(value, "^The field (?<field>.+?) and (?<other>.+?) must match\\.$", RegexOptions.CultureInvariant);
        if (compare.Success)
            return $"يجب أن يتطابق حقلا {LocalizeField(compare.Groups["field"].Value)} و{LocalizeField(compare.Groups["other"].Value)}.";

        return null;
    }

    private static string LocalizeField(string field) => field switch
    {
        "Email" => "البريد الإلكتروني",
        "Password" => "كلمة المرور",
        "NewPassword" => "كلمة المرور الجديدة",
        "ConfirmPassword" => "تأكيد كلمة المرور",
        "Name" => "الاسم",
        "Price" => "السعر",
        _ => Arabic.TryGetValue(field, out var localized) ? localized : field
    };
}
