<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>RestaurantMenuPlatform.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Application\Application.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.19" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.0.20" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.19">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
